schema: src/lib/graphql/generated/schema.graphql
documents:
  - src/lib/graphql/**.graphql
generates:
  src/lib/graphql/generated/types.ts:
    - typescript
  src/lib/graphql/generated/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
      - typescript-urql
    config:
      documentMode: documentNode
      immutableTypes: false
      withComponent: false
      withHooks: true
      enumsAsConst: true
      namingConvention:
        enumValues: upper-case#upperCase
